version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poc_db
    ports:
      - "3307:3306"
  cassandra1:
    image: cassandra:3.11.8
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9242:9042"